project:
  type: website
  output-dir: _site

format:
  revealjs:
    theme: [default]
    css: styles.css
    slide-number: true
    toc: false
    incremental: false
    highlight-style: github
    code-fold: false
    df-print: default
    preview-links: auto
    transition: slide
    progress: true
    chalkboard: false
    controls: true
    center: false

execute:
  freeze: false
  echo: true
  warning: false
  message: false

metadata-files: []

website:
  title: "Introduction to VBA and Python"
  navbar:
    right:
      - text: Home
        href: README.md
      - text: Day 1 — Intro to VBA
        href: slides/vba/01-intro-vba.qmd
