name: vba-python-course
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=2.0
  - pandas=2.2
  - scipy=1.13
  - polars=1.5
  - dask=2024.8.0
  - flask=3.0
  - pip
  - pip:
    - streamlit==1.37.0
    - yfinance==0.2.40
